name: deploy-prod
run-name: ${{ github.event.workflow_run.head_commit.message }}

on:
  push:
    tags:
      - '*'

jobs:
  prod-run:
    uses: reusable-templates/.github/workflows/deploy-github.yaml@v1.3.3
  with:
    file-path: environments/configuration-management-prod.yaml
    branch: main
    target-env: prod-au
  secrets: inherit